spring:
  application:
    name: core
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTHENTIK_JWK_URI:http://localhost:9000/application/o/taekwondo-web/jwks/}
          issuer-uri: ${AUTHENTIK_ISSUER_URI:http://localhost:9000/application/o/taekwondo-web/}

authentik:
  base-url: ${AUTHENTIK_BASE_URL:http://localhost:9000}
