ALTER TABLE federations 
  ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  ADD COLUMN created_by BIGINT NOT NULL DEFAULT 1,
  ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN updated_by BIGINT;
